from github import Github, GithubException
import re
import feedparser
import os

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO_NAME = "VecorDEV/dati-finanziari"

# Salva il file HTML nella cartella 'results'
file_path = "results/classifica.html"
news_path = "results/news.html"
    
# Salva il file su GitHub
github = Github(GITHUB_TOKEN)
repo = github.get_repo(REPO_NAME)


# Lista dei simboli azionari da cercare
symbol_list = ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "V", "JPM", "JNJ", "WMT",
        "NVDA", "PYPL", "DIS", "NFLX", "NIO", "NRG", "ADBE", "INTC", "CSCO", "PFE",
        "KO", "PEP", "MRK", "ABT", "XOM", "CVX", "T", "MCD", "NKE", "HD",
        "IBM", "CRM", "BMY", "ORCL", "ACN", "LLY", "QCOM", "HON", "COST", "SBUX",
        "CAT", "LOW", "MS", "GS", "AXP", "INTU", "AMGN", "GE", "FIS", "CVS",
        "DE", "BDX", "NOW", "SCHW", "LMT", "ADP", "C", "PLD", "NSC", "TMUS",
        "ITW", "FDX", "PNC", "SO", "APD", "ADI", "ICE", "ZTS", "TJX", "CL",
        "MMC", "EL", "GM", "CME", "EW", "AON", "D", "PSA", "AEP", "TROW", 
        "LNTH", "HE", "BTDR", "NAAS", "SCHL", "TGT", "SYK", "BKNG", "DUK", "USB",
        "EURUSD", "USDJPY", "GBPUSD", "AUDUSD", "USDCAD", "USDCHF", "NZDUSD", "EURGBP", "EURJPY", "GBPJPY",
        "AUDJPY", "CADJPY", "CHFJPY", "EURAUD", "EURNZD", "EURCAD", "EURCHF", "GBPCHF", "GBPJPY", "AUDCAD",
        "BTCUSD", "ETHUSD", "LTCUSD", "XRPUSD", "BCHUSD", "EOSUSD", "XLMUSD", "ADAUSD", "TRXUSD", "NEOUSD",
        "DASHUSD", "XMRUSD", "ETCUSD", "ZECUSD", "BNBUSD", "DOGEUSD", "USDTUSD", "LINKUSD", "ATOMUSD", "XTZUSD",
        "COCOA", "XAUUSD", "XAGUSD", "OIL"]  # Puoi aggiungere altri simboli

def get_stock_news(symbol):
    """ Recupera i titoli delle notizie per un determinato simbolo. """
    url = f"https://news.google.com/rss/search?q={symbol}+stock&hl=en-US&gl=US&ceid=US:en"
    feed = feedparser.parse(url)
    
    titles = [entry.title for entry in feed.entries]
    #print(titles)
    return titles

# Dizionario di parole chiave con il loro punteggio di sentiment
# Dataset esteso di parole e frasi con i rispettivi punteggi
sentiment_dict = {
    "acquisition": 0.7,
    "acquisitions": 0.7,
    "appreciation": 0.9,
    "assets": 0.8,
    "asset": 0.8,
    "advance": 0.8,
    "advanced": 0.8,
    "agreement": 0.7,
    "agreements": 0.7,
    "agree": 0.7,
    "agreed": 0.6,
    "allocation": 0.6,
    "arbitrage": 0.5,
    "augmented": 0.7,
    "attraction": 0.7,
    "attractions": 0.7,
    "affluence": 0.9,
    "accelerator": 0.7,
    "ascend": 0.8,
    "advantage": 0.8,
    "advantaged": 0.8,
    "amplification": 0.7,
    "abundance": 0.9,
    "amendment": 0.6,
    "allowance": 0.6,
    "achievement": 0.8,
    "accession": 0.7,
    "ascension": 0.8,
    "allocation": 0.6,
    "acceptance": 0.7,
    "announcement": 0.5,
    "assessment": 0.5,
    "accreditation": 0.6,
    "authorization": 0.6,
    "authorized": 0.6,
    "assurance": 0.7,
    "advancement": 0.8,
    "aspiration": 0.7,
    "activation": 0.6,
    "adjustment": 0.5,
    "assignment": 0.5,
    "appropriation": 0.5,
    "adoption": 0.6,
    "achievement": 0.8,
    "acceleration": 0.8,
    "announcement": 0.5,
    "appraisal": 0.6,
    "amortization": 0.4,
    "arrest": 0.1,
    "arrested": 0.1,
    "arrests": 0.1,
    "adversity": 0.2,
    "anomaly": 0.3,
    "attrition": 0.2,
    "antitrust": 0.2,
    "aversion": 0.2,
    "arrears": 0.1,
    "abandonment": 0.1,
    "alienation": 0.2,
    "asymmetry": 0.3,
    "ambiguity": 0.3,
    "anxiety": 0.2,
    "arbitration": 0.5,
    "adjustment": 0.5,
    "austerity": 0.3,
    "audit": 0.4,
    "amendment": 0.6,
    "apprehension": 0.2,
    "abrogation": 0.1,
    "annulment": 0.1,
    "annual": 0.6,
    "arrogation": 0.1,
    "admonition": 0.2,
    "antagonism": 0.2,
    "abysmal": 0.1,
    "accountability": 0.6,
    "arrestment": 0.2,
    "attrition": 0.3,
    "aftermath": 0.2,
    
    "bullish": 0.9,
    "bully": 0.7,
    "bankruptcy": 0.1,
    "balance": 0.7,
    "balanced": 0.6,
    "bomb": 0.6,
    "buy": 0.8,
    "buys": 0.8,
    "bought": 0.7,
    "boost": 0.8,
    "boosts": 0.8,
    "boosted": 0.8,
    "benefit": 0.8,
    "benefits": 0.8,
    "billion": 0.7,
    "billions": 0.7,
    "borrow": 0.5,
    "bonds": 0.7,
    "breakthrough": 0.8,
    "benchmark": 0.7,
    "bust": 0.2,
    "bargain": 0.8,
    "broker": 0.6,
    "brokers": 0.6,
    "boom": 0.9,
    "bank": 0.7,
    "budget": 0.6,
    "bid": 0.7,
    "bailout": 0.3,
    "beneficiary": 0.7,
    "bipartisan": 0.6,
    "blockchain": 0.6,
    "banknotes": 0.6,
    "bail": 0.3,
    "banking": 0.7,
    "barrier": 0.3,
    "bottom line": 0.6,
    "balance sheet": 0.7,
    "bull": 0.9,
    "backlog": 0.4,
    "budgeting": 0.5,
    "backer": 0.6,
    "brisk": 0.7,
    "bankable": 0.7,
    "burnout": 0.2,
    "barometer": 0.6,
    "benchmarking": 0.6,
    "blockbuster": 0.8,
    "balance of payments": 0.6,
    "breach": 0.2,
    "blowout": 0.1,
    "bribe": 0.0,
    "brutal": 0.1,
    "bust up": 0.2,
    "bank run": 0.1,

    "capital": 0.8,
    "cash": 0.8,
    "crash": 0.1,
    "cautious": 0.3,
    "climb": 0.8,
    "climbed": 0.7,
    "climbs": 0.8,
    "coup": 0.2,
    "contract": 0.6,
    "contracts": 0.6,
    "consumer": 0.7,
    "consumers": 0.7,
    "capitalism": 0.7,
    "credit": 0.7,
    "credit card": 0.6,
    "cut": 0.3,
    "climate": 0.7,
    "collapse": 0.1,
    "creditor": 0.6,
    "currency": 0.6,
    "commodities": 0.7,
    "change": 0.6,
    "company": 0.7,
    "consumerism": 0.6,
    "competition": 0.7,
    "coupon": 0.6,
    "contribution": 0.7,
    "crisis": 0.1,
    "consolidation": 0.6,
    "capitalization": 0.8,
    "collateral": 0.5,
    "compliance": 0.6,
    "collaboration": 0.7,
    "consumer confidence": 0.8,
    "credibility": 0.7,
    "closure": 0.3,
    "cost": 0.4,
    "commitment": 0.7,
    "clawback": 0.3,
    "cutback": 0.3,
    "contraction": 0.3,
    "conservative": 0.4,
    "corruption": 0.0,
    "capital gains": 0.8,
    "cash flow": 0.7,
    "credit rating": 0.6,
    "contribution margin": 0.7,
    "crisis management": 0.3,
    "correlation": 0.5,
    "capital-raise": 0.7,
    "compensation": 0.6,
    "consequence": 0.4,
    "covenant": 0.5,
    "circulation": 0.6,
    "counterfeit": 0.1,
    "convergence": 0.7,
    "compensation package": 0.7,
    "compensation": 0.7,
    "capital flow": 0.6,
    "corruption scandal": 0.1,
    
    "debt": 0.2,
    "dividend": 0.8,
    "deficit": 0.1,
    "decline": 0.2,
    "depreciation": 0.3,
    "drop": 0.2,
    "demand": 0.8,
    "default": 0.1,
    "downturn": 0.2,
    "devaluation": 0.3,
    "disruption": 0.3,
    "disposal": 0.5,
    "discount": 0.6,
    "dilution": 0.4,
    "development": 0.7,
    "derivatives": 0.5,
    "declining": 0.3,
    "distribution": 0.6,
    "debt ceiling": 0.2,
    "decline rate": 0.2,
    "dominance": 0.7,
    "deregulation": 0.5,
    "distressed": 0.2,
    "downsize": 0.3,
    "drain": 0.2,
    "delisting": 0.1,
    "doubt": 0.2,
    "diminish": 0.3,
    "declining market": 0.3,
    "deterioration": 0.2,
    "diversification": 0.7,
    "direct investment": 0.7,
    "downward": 0.2,
    "danger": 0.1,
    "decline in-sales": 0.2,
    "debt reduction": 0.6,
    "discrepancy": 0.3,
    "debt to equity": 0.4,
    "dismantling": 0.3,
    "deflation": 0.2,
    "debtor": 0.3,
    "debt servicing": 0.3,
    "dominant": 0.7,
    "diversified": 0.7,
    "dormant": 0.3,
    "downward spiral": 0.2,
    "dysfunction": 0.1,
    "dollars": 0.7,
    "dollar": 0.7,

    "equity": 0.8,
    "earnings": 0.8,
    "emerging": 0.7,
    "expansion": 0.8,
    "efficiency": 0.7,
    "exit": 0.5,
    "estimation": 0.7,
    "expenditure": 0.5,
    "enterprise": 0.7,
    "evaluation": 0.6,
    "euro": 0.7,
    "equilibrium": 0.6,
    "economic": 0.7,
    "endowment": 0.7,
    "elevate": 0.8,
    "exceed": 0.8,
    "expectation": 0.7,
    "excess": 0.3,
    "enrichment": 0.8,
    "evidence": 0.6,
    "exposure": 0.5,
    "encouragement": 0.7,
    "evaluation": 0.6,
    "enterprise value": 0.7,
    "employer": 0.6,
    "equity market": 0.7,
    "extraction": 0.5,
    "exclusivity": 0.7,
    "escrow": 0.6,
    "emission": 0.5,
    "exodus": 0.2,
    "evasion": 0.1,
    "equitable": 0.7,
    "equilibrium price": 0.6,
    "empowerment": 0.7,
    "examination": 0.5,
    "empirical": 0.6,
    "effort": 0.7,
    "equivalent": 0.6,
    "elasticity": 0.6,
    "entitlement": 0.6,
    "enactment": 0.5,
    "enforce": 0.6,
    "establishment": 0.7,
    "enlightenment": 0.7,
    "equity fund": 0.7,

    "financial": 0.8,
    "fund": 0.8,
    "forecast": 0.7,
    "failure": 0.2,
    "fluctuation": 0.3,
    "funding": 0.7,
    "profit": 0.8,
    "flexibility": 0.7,
    "favorable": 0.8,
    "fall": 0.2,
    "fraud": 0.1,
    "fiscal": 0.6,
    "futures": 0.6,
    "fee": 0.5,
    "flow": 0.7,
    "facility": 0.6,
    "focus": 0.7,
    "fintech": 0.7,
    "finance": 0.8,
    "foreign": 0.6,
    "fast track": 0.7,
    "foreclosure": 0.1,
    "failing": 0.2,
    "frenzy": 0.3,
    "fallout": 0.2,
    "failure rate": 0.2,
    "fundamentals": 0.7,
    "freeze": 0.3,
    "flare": 0.2,
    "forecasting": 0.7,
    "fraudulent": 0.1,
    "favorable outlook": 0.8,
    "financing": 0.7,
    "fifth quarter": 0.6,
    "fractional": 0.6,
    "federal": 0.6,
    "flow through": 0.7,
    "forward looking": 0.7,
    "fledgling": 0.5,
    "fire sale": 0.1,
    "full disclosure": 0.7,
    "financial innovation": 0.7,
    "fiscal policy": 0.6,
    "free market": 0.7,
    "falling prices": 0.3,
    "falling price": 0.3,
    "falling": 0.3,

    "growth": 0.8,
    "growths": 0.8,
    "gain": 0.9,
    "gains": 0.9,
    "growth rate": 0.8,
    "gains": 0.9,
    "guarantee": 0.8,
    "government": 0.7,
    "gross": 0.7,
    "global": 0.7,
    "green": 0.8,
    "grants": 0.7,
    "guidance": 0.7,
    "glut": 0.2,
    "gap": 0.3,
    "gloom": 0.2,
    "grave": 0.1,
    "gridlock": 0.3,
    "grind": 0.3,
    "gross margin": 0.7,
    "gross product": 0.7,
    "gains per share": 0.8,
    "geopolitical": 0.6,
    "gdp": 0.7,
    "greenfield": 0.7,
    "governance": 0.6,
    "garnishment": 0.2,
    "growing market": 0.8,
    "government debt": 0.3,
    "garnishee": 0.2,
    "globalization": 0.6,
    "grip": 0.3,
    "gap analysis": 0.5,
    "global demand": 0.7,
    "gains tax": 0.5,
    "gross revenue": 0.7,
    "goodwill": 0.6,
    "graft": 0.1,
    "gold": 0.8,
    "guarantor": 0.6,
    "growth stock": 0.8,
    "good debt": 0.7,
    "global recession": 0.2,

    "hike": 0.8,
    "high": 0.8,
    "highs": 0.8,
    "hub": 0.6,
    "hedge": 0.7,
    "holding": 0.7,
    "holdings": 0.7,
    "hit": 0.3,
    "hurdle": 0.4,
    "harvest": 0.7,
    "healthy": 0.8,
    "hoarding": 0.2,
    "heading": 0.6,
    "headwind": 0.3,
    "headline": 0.6,
    "hedging": 0.7,
    "hyperinflation": 0.2,
    "high risk": 0.3,
    "high risks": 0.3,
    "hedge fund": 0.6,
    "housing": 0.7,
    "holding company": 0.7,
    "harmonic": 0.6,
    "high yield": 0.7,
    "healthy growth": 0.8,
    "hypothetical": 0.5,
    "haircut": 0.2,
    "hold": 0.6,
    "harness": 0.7,
    "hype": 0.4,
    "high performance": 0.8,
    "household": 0.6,
    "high value": 0.8,
    "hollow": 0.2,
    "hunting": 0.6,
    "headcount": 0.6,
    "hasty": 0.3,
    "healthcare": 0.7,
    "hustle": 0.4,
    "hardship": 0.2,
    "hard asset": 0.7,
    "hollowed out": 0.2,
    "heightened": 0.3,
    "heavily indebted": 0.2,
    "harbinger": 0.3,

    "income": 0.8,
    "investment": 0.8,
    "inflation": 0.3,
    "inflate": 0.3,
    "increase": 0.7,
    "impact": 0.6,
    "improvement": 0.8,
    "interest": 0.7,
    "insight": 0.7,
    "insights": 0.7,
    "investor": 0.8,
    "indicator": 0.6,
    "inflationary": 0.3,
    "innovative": 0.8,
    "insurance": 0.7,
    "initial": 0.6,
    "institution": 0.7,
    "integrity": 0.8,
    "investment grade": 0.7,
    "intelligence": 0.7,
    "increase rate": 0.6,
    "inventory": 0.6,
    "indebtedness": 0.2,
    "interest rate": 0.6,
    "impactful": 0.7,
    "incursion": 0.3,
    "illiquid": 0.2,
    "illiquidity": 0.2,
    "infrastructure": 0.7,
    "impairment": 0.2,
    "insolvency": 0.1,
    "income tax": 0.4,
    "incentive": 0.7,
    "issue": 0.5,
    "input": 0.6,
    "inflated": 0.3,
    "inflating": 0.3,
    "insider": 0.5,
    "intangible": 0.6,
    "increased demand": 0.7,
    "internal": 0.6,
    "independent": 0.7,
    "invest": 0.8,
    "incorporation": 0.6,
    "illegal": 0.1,
    "intervention": 0.4,
    "investing": 0.8,
    "impaired": 0.2,
    "interest bearing": 0.7,
    "interest": 0.7,
    "interesting": 0.6,
    "interested": 0.7,

    "job": 0.7,
    "jobs": 0.7,
    "judgment": 0.6,
    "judgments": 0.6,
    "joint": 0.7,
    "jump": 0.8,
    "jumps": 0.8,
    "junks": 0.2,
    "junk": 0.2,
    "justice": 0.8,
    "juncture": 0.5,
    "justification": 0.6,
    "jittery": 0.3,
    "journey": 0.7,
    "juggle": 0.5,
    "jackpot": 0.9,
    "jackpots": 0.9,
    "jockey": 0.6,
    "jumpstart": 0.8,
    "juggernaut": 0.7,
    "jockeying": 0.6,
    "justice system": 0.6,
    "job market": 0.7,
    "jack up": 0.3,
    "judicious": 0.7,
    "jobless": 0.2,

    "key": 0.7,
    "keys": 0.7,
    "knowledge": 0.7,
    "kpi": 0.7,
    "kingdom": 0.6,
    "kicker": 0.6,
    "knockout": 0.7,
    "keep": 0.6,
    "keynote": 0.7,
    "keystone": 0.7,
    "knot": 0.3,
    "kickback": 0.2,
    "keen": 0.7,
    "kettle": 0.5,
    "kill": 0.2,
    "key player": 0.8,
    "kind": 0.6,
    "kerfuffle": 0.3,
    "kickstart": 0.7,
    "knock on": 0.4,
    "knocks on": 0.4,
    "knocked on": 0.4,
    "kudos": 0.8,

    "loss": 0.2,
    "losses": 0.2,
    "lost": 0.2,
    "liquidity": 0.6,
    "loan": 0.7,
    "leveraged": 0.5,
    "liability": 0.3,
    "liquid": 0.7,
    "long": 0.7,
    "lift": 0.8,
    "low": 0.3,
    "leading": 0.8,
    "leverage": 0.6,
    "lending": 0.7,
    "losses": 0.2,
    "lead": 0.8,
    "lag": 0.4,
    "liquidation": 0.1,
    "low risk": 0.7,
    "low risks": 0.7,
    "low cost": 0.7,
    "limit": 0.5,
    "limits": 0.5,
    "limited": 0.5,
    "lucrative": 0.9,
    "late": 0.3,
    "lack": 0.2,
    "long term": 0.8,
    "long terms": 0.8,
    "law": 0.6,
    "large cap": 0.7,
    "lookout": 0.6,
    "line item": 0.5,
    "long position": 0.7,
    "long positions": 0.7,
    "leading indicator": 0.7,
    "liquid assets": 0.7,
    "lull": 0.3,
    "leveraged buyout": 0.6,
    "low growth": 0.3,
    "loss making": 0.2,
    "leveraging": 0.6,
    "limited": 0.5,
    "launch": 0.7,
    "low value": 0.3,
    "lifetime value": 0.7,
    "liquidate": 0.1,

    "market": 0.8,
    "markets": 0.8,
    "management": 0.7,
    "money": 0.8,
    "merger": 0.8,
    "magnitude": 0.7,
    "margin": 0.7,
    "momentum": 0.8,
    "move": 0.7,
    "moves": 0.7,
    "moved": 0.7,
    "maturity": 0.7,
    "million": 0.7,
    "monitor": 0.6,
    "master": 0.8,
    "markup": 0.7,
    "minimize": 0.7,
    "maximization": 0.8,
    "maximizations": 0.8,
    "market share": 0.8,
    "multiplier": 0.7,
    "mechanism": 0.7,
    "material": 0.6,
    "modest": 0.6,
    "manipulation": 0.2,
    "marketplace": 0.7,
    "margin call": 0.3,
    "move up": 0.8,
    "moves up": 0.8,
    "moved up": 0.7,
    "marginal": 0.6,
    "model": 0.7,
    "medium": 0.6,
    "money market": 0.7,
    "manufacture": 0.7,
    "monetary": 0.7,
    "markup pricing": 0.7,
    "monthly": 0.6,
    "maturity date": 0.7,
    "monitoring": 0.6,
    "market risk": 0.4,
    "market risks": 0.4,
    "mid term": 0.6,
    "mid terms": 0.6,
    "money supply": 0.6,
    "move forward": 0.7,
    "modification": 0.6,
    "mining": 0.6,
    "multinational": 0.7,
    "multinationals": 0.7,
    "market value": 0.8,
    "market values": 0.8,

    "net": 0.8,
    "neutral": 0.5,
    "niche": 0.7,
    "negotiation": 0.7,
    "note": 0.6,
    "narrative": 0.6,
    "non performing": 0.2,
    "nominal": 0.6,
    "nucleus": 0.7,
    "narrow": 0.4,
    "national": 0.6,
    "new": 0.7,
    "nondiscretionary": 0.6,
    "negative": 0.2,
    "next": 0.6,
    "nonprofit": 0.7,
    "new product": 0.7,
    "new products": 0.7,
    "non cash": 0.6,
    "net profit": 0.8,
    "net profits": 0.8,
    "note worthy": 0.7,
    "non essential": 0.3,
    "net worth": 0.8,
    "narrative driven": 0.6,
    "nurture": 0.7,
    "non compliant": 0.2,
    "nervous": 0.3,
    "non recourse": 0.5,
    "no growth": 0.3,
    "no growths": 0.3,
    "new investment": 0.8,
    "new investments": 0.8,
    "nominated": 0.6,
    "non cyclical": 0.7,
    "noteworthy": 0.7,
    "negotiable": 0.6,
    "normalization": 0.7,
    "non disclosure": 0.5,
    "net gain": 0.8,
    "net gains": 0.8,

    "offer": 0.7,
    "offers": 0.7,
    "offered": 0.6,
    "outlook": 0.7,
    "outlooks": 0.7,
    "option": 0.7,
    "options": 0.7,
    "overperform": 0.8,
    "outperform": 0.8,
    "optimistic": 0.8,
    "opportunity": 0.8,
    "opportunities": 0.8,
    "organic": 0.7,
    "overdue": 0.3,
    "overhead": 0.5,
    "overvalued": 0.2,
    "obligation": 0.4,
    "obligations": 0.4,
    "ownership": 0.7,
    "offset": 0.6,
    "outflow": 0.3,
    "overleveraged": 0.2,
    "operational": 0.6,
    "overhaul": 0.6,
    "optionality": 0.7,
    "opting": 0.6,
    "overestimate": 0.3,
    "outstanding": 0.8,
    "overcapacity": 0.3,
    "overreaction": 0.3,
    "overexposure": 0.3,
    "overperformance": 0.8,
    "obsolescence": 0.2,
    "outsourcing": 0.6,
    "overfunded": 0.7,
    "optimization": 0.7,
    "optimizations": 0.7,
    "operating profit": 0.8,
    "overstretch": 0.3,
    "oversupply": 0.2,
    "offerings": 0.7,
    "on track": 0.7,
    "overcome": 0.8,
    "oscillation": 0.4,
    "overproduction": 0.3,
    "organic growth": 0.8,
    "organic growths": 0.8,

    "profit": 0.8,
    "profits": 0.8,
    "positive": 0.9,
    "payment": 0.7,
    "payments": 0.7,
    "performance": 0.8,
    "price": 0.7,
    "prices": 0.7,
    "premium": 0.8,
    "payout": 0.8,
    "potential": 0.8,
    "portfolio": 0.7,
    "predict": 0.7,
    "position": 0.7,
    "positions": 0.7,
    "production": 0.6,
    "public": 0.6,
    "pioneer": 0.8,
    "purchasing": 0.7,
    "prosper": 0.9,
    "plan": 0.8,
    "plans": 0.8,
    "positive growth": 0.8,
    "positive growths": 0.8,
    "payoff": 0.8,
    "peaking": 0.7,
    "private": 0.7,
    "potentially": 0.7,
    "price increase": 0.8,
    "power": 0.7,
    "prospects": 0.8,
    "project": 0.7,
    "pivot": 0.6,
    "price-cut": 0.3,
    "price target": 0.7,
    "plunge": 0.2,
    "plunges": 0.2,
    "plunged": 0.2,
    "pressure": 0.3,
    "profit margin": 0.8,
    "pandemic": 0.2,
    "pessimistic": 0.2,
    "public offering": 0.7,
    "payback": 0.7,
    "plentiful": 0.8,
    "post tax": 0.6,
    "penetration": 0.7,
    "payable": 0.7,
    "premium rate": 0.8,
    "plunge risk": 0.3,
    "poor performance": 0.2,
    "poor": 0.1,
    "progress": 0.8,

    "quality": 0.8,
    "quota": 0.7,
    "quantitative": 0.7,
    "quick": 0.8,
    "quarantine": 0.2,
    "questionable": 0.3,
    "quiet": 0.5,
    "quicksilver": 0.6,
    "quantum": 0.7,
    "quote": 0.6,
    "qualitative": 0.7,
    "quantify": 0.6,
    "quasi": 0.5,
    "quick turnaround": 0.8,
    "quarter": 0.7,
    "qualify": 0.7,
    "quench": 0.6,
    "quarterly": 0.7,
    "quality control": 0.7,
    "quaint": 0.6,

    "revenue": 0.8,
    "revenues": 0.8,
    "recovery": 0.9,
    "reinvestment": 0.8,
    "reduction": 0.3,
    "reductions": 0.3,
    "resilience": 0.8,
    "risk": 0.2,
    "risks": 0.2,
    "return": 0.8,
    "restructuring": 0.4,
    "reputation": 0.7,
    "robust": 0.8,
    "recession": 0.1,
    "rebalancing": 0.7,
    "revenue growth": 0.8,
    "revenue growths": 0.8,
    "reliable": 0.8,
    "reform": 0.7,
    "real estate": 0.7,
    "raise": 0.8,
    "revaluation": 0.7,
    "retention": 0.7,
    "relocation": 0.6,
    "refinancing": 0.6,
    "reduction in force": 0.3,
    "risk aversion": 0.3,
    "rally": 0.8,
    "recovery plan": 0.8,
    "reliable performance": 0.8,
    "reinforcement": 0.7,
    "reinvestment strategy": 0.8,
    "risky": 0.2,
    "repayment": 0.7,
    "retirement fund": 0.7,
    "recessionary": 0.2,
    "redemption": 0.7,
    "revenue stream": 0.8,
    "revenue model": 0.8,
    "reserves": 0.7,
    "revenue per share": 0.8,
    
    "share": 0.8,
    "shares": 0.8,
    "shared": 0.8,
    "stock": 0.8,
    "stocks": 0.8,
    "surge": 0.8,
    "strong": 0.9,
    "strategy": 0.8,
    "strategies": 0.8,
    "successful": 0.9,
    "savings": 0.7,
    "sustainability": 0.8,
    "stability": 0.8,
    "securities": 0.7,
    "supply": 0.7,
    "security": 0.8,
    "steady": 0.7,
    "subsidy": 0.7,
    "startup": 0.8,
    "startups": 0.8,
    "solid": 0.8,
    "shareholder": 0.8,
    "sell": 0.3,
    "sold out": 0.7,
    "specialist": 0.7,
    "spend": 0.5,
    "surplus": 0.8,
    "stimulus": 0.8,
    "short": 0.3,
    "savings plan": 0.7,
    "stagnation": 0.2,
    "scalability": 0.8,
    "survival": 0.6,
    "seasonality": 0.6,
    "softening": 0.3,
    "saturation": 0.4,
    "settlement": 0.6,
    "shutdown": 0.2,
    "squeeze": 0.3,
    "sale": 0.7,
    "synergy": 0.8,
    "share price": 0.8,
    "spin off": 0.7,
    "stimulation": 0.7,
    "speed": 0.7,
    "stagnant": 0.2,
    "stock market": 0.8,
    
    "tax": 0.4,
    "taxes": 0.4,
    "taxed": 0.2,
    "target": 0.8,
    "targets": 0.8,
    "trade": 0.7,
    "trend": 0.7,
    "trends": 0.7,
    "transaction": 0.7,
    "turnaround": 0.8,
    "total": 0.7,
    "tangible": 0.8,
    "treasury": 0.8,
    "trust": 0.8,
    "transaction cost": 0.6,
    "tender": 0.7,
    "technology": 0.8,
    "tactical": 0.7,
    "takeover": 0.7,
    "tailwind": 0.8,
    "taxation": 0.5,
    "tighten": 0.3,
    "test": 0.6,
    "trade off": 0.6,
    "transactional": 0.6,
    "tactical position": 0.7,
    "targeted": 0.7,
    "tangible asset": 0.8,
    "timeframe": 0.6,
    "turbulence": 0.2,
    "trouble": 0.2,
    "troubles": 0.2,
    "transparency": 0.8,
    "transition": 0.7,
    "total return": 0.8,
    "top line": 0.7,
    "turnkey": 0.7,
    "trigger": 0.6,
    "turmoil": 0.2,
    "tracking": 0.6,
    "trading": 0.7,
    "takedown": 0.3,
    "tax reform": 0.5,
    "tax reformed": 0.4,
    
    "underperform": 0.2,
    "unemployment": 0.1,
    "upturn": 0.8,
    "underwriting": 0.6,
    "unsecured": 0.3,
    "unforeseen": 0.3,
    "utility": 0.7,
    "utilities": 0.7,
    "unified": 0.7,
    "unfavorable": 0.2,
    "unpredictable": 0.3,
    "usury": 0.1,
    "unit": 0.6,
    "units": 0.6,
    "upside": 0.8,
    "upgrade": 0.8,
    "upgraded": 0.8,
    "upgrades": 0.8,
    "urgent": 0.6,
    "underutilized": 0.4,
    "unavailable": 0.3,
    "unrealized": 0.5,
    "uncovered": 0.3,
    "unsustainable": 0.2,
    "unprofitable": 0.2,
    "unfavorable trend": 0.2,
    "uncertainty": 0.3,
    "uncertain": 0.3,
    "underperformance": 0.2,
    "under": 0.2,
    "utilization": 0.7,
    "upward": 0.8,
    "uncapped": 0.7,
    "unquestionable": 0.8,
    "unlimited": 0.8,
    "unpredictability": 0.3,

    "value": 0.8,
    "values": 0.8,
    "volatility": 0.3,
    "volume": 0.7,
    "volumes": 0.7,
    "viability": 0.8,
    "venture": 0.7,
    "vulnerable": 0.2,
    "valuation": 0.8,
    "valuations": 0.8,
    "victory": 0.9,
    "victories": 0.9,
    "volunteer": 0.6,
    "violation": 0.2,
    "violations": 0.2,
    "vacancy": 0.3,
    "viable": 0.8,
    "verifiable": 0.7,
    "verdict": 0.6,
    "voluntary": 0.7,
    "variable": 0.7,
    "venture capital": 0.7,
    "vow": 0.8,
    "virtual": 0.6,
    "visibility": 0.7,
    "visible": 0.6,
    "vanguard": 0.8,
    "valuation risk": 0.3,
    "vigor": 0.8,
    "vantage": 0.8,
    "vantages": 0.8,
    "volatile": 0.2,
    "victimized": 0.1,
    "vicious": 0.1,
    "valiant": 0.8,
    "verification": 0.7,
    "void": 0.2,
    "vulnerability": 0.2,
    "vulnerabilities": 0.2,
    "volume trading": 0.7,
    "value creation": 0.8,
    "vertical": 0.6,

    "wealth": 0.9,
    "win": 0.9,
    "wins": 0.9,
    "won": 0.9,
    "wage": 0.7,
    "warrant": 0.7,
    "weakness": 0.2,
    "weaknesses": 0.2,
    "weak": 0.2,
    "withdrawal": 0.3,
    "withdrawals": 0.3,
    "wave": 0.6,
    "waves": 0.6,
    "wealthy": 0.8,
    "widening": 0.6,
    "wholesale": 0.7,
    "well being": 0.8,
    "workforce": 0.7,
    "worst case": 0.2,
    "warning": 0.2,
    "will": 0.8,
    "winners": 0.9,
    "win win": 0.9,
    "worth": 0.8,
    "write off": 0.2,
    "workplace": 0.7,
    "withdraw": 0.3,
    "wage growth": 0.7,
    "wage": 0.6,
    "wages": 0.6,
    "wager": 0.6,
    "waterfall": 0.6,
    "waterfalls": 0.6,
    "worsen": 0.2,
    "weaken": 0.2,
    "waiting": 0.5,
    "widen": 0.6,
    "worry": 0.2,
    "worried": 0.2,
    "welfare": 0.8,
    "whipsaw": 0.2,
    "wild": 0.3,
    "winds": 0.6,
    "worldwide": 0.7,
    "web": 0.6,
    "workload": 0.5,
    
    "x efficiency": 0.7,
    "x factor": 0.8,
    "xenocurrency": 0.6,
    "xenophobic": 0.2,
    "xerox effect": 0.5,
    "xit": 0.3,

    "yield": 0.8,
    "yearly": 0.7,
    "year": 0.6,
    "yields curve": 0.7,
    "young market": 0.4,
    "young": 0.4,
    "yen": 0.6,
    "yoy": 0.8,
    "yellow flag": 0.3,
    "yield spread": 0.7,
    "yield growth": 0.8,
    "yield risk": 0.3,
    "yield risks": 0.3,

    "zero": 0.5,
    "z score": 0.7,
    "zombie company": 0.2,
    "zombie bank": 0.2,
    "zoning": 0.6,
    "zigzag market": 0.4,
    "zig zag": 0.4,
    "zigzag": 0.4,
    "zenith": 0.8,
    "zero coupon": 0.6,
    "zero inflation": 0.7,
    "zero sum": 0.4
}


def normalize_text(text):
    """ Pulisce e normalizza il testo per una migliore corrispondenza. """
    text = text.lower()  # Converti tutto in minuscolo
    text = re.sub(r'[-_/]', ' ', text)  # Sostituisci trattini e underscore con spazi
    text = re.sub(r'\s+', ' ', text).strip()  # Rimuovi spazi multipli e spazi iniziali/finali
    return text

def calculate_sentiment(titles):
    """ Calcola il sentiment medio di una lista di titoli di notizie con normalizzazione. """
    total_sentiment = 0
    num_titles = len(titles)
    
    for title in titles:
        normalized_title = normalize_text(title)  # Normalizza il titolo
        sentiment_score = 0
        count = 0

        for keyword, score in sentiment_dict.items():
            if re.search(r'\b' + re.escape(keyword) + r'\b', normalized_title):
                sentiment_score += score
                count += 1

        if count != 0:
            total_sentiment += (sentiment_score / count)

    if num_titles > 0:
        average_sentiment = total_sentiment / num_titles
    else:
        average_sentiment = 0  # Se non ci sono titoli, il sentiment è 0
    
    return average_sentiment

def get_sentiment_for_all_symbols(symbol_list):
    sentiment_results = {}
    all_news_entries = []  # Lista per salvare tutti i titoli e sentimenti
    
    for symbol in symbol_list:
        titles = get_stock_news(symbol)
        sentiment = calculate_sentiment(titles)
        sentiment_results[symbol] = sentiment

        file_path = f"results/{symbol.upper()}_RESULT.html"
        html_content = [f"<html><head><title>Previsione per {symbol}</title></head><body>",
                        f"<h1>Previsione per: ({symbol})</h1>",
                        "<table border='1'><tr><th>Probability</th></tr>",
                        f"<tr><td>{sentiment * 100:.2f}%</td></tr>",
                        "</table></body></html>"]

        try:
            contents = repo.get_contents(file_path)
            repo.update_file(contents.path, f"Updated probability for {symbol}", "\n".join(html_content), contents.sha)
        except GithubException:
            repo.create_file(file_path, f"Created probability for {symbol}", "\n".join(html_content))

        # Aggiungi le notizie e i sentimenti alla lista per il file `news.html`
        for title in titles:
            title_sentiment = calculate_sentiment([title])  # Calcola il sentiment specifico del titolo
            all_news_entries.append((symbol, title, title_sentiment))

    return sentiment_results, all_news_entries

# Calcolare il sentiment medio per ogni simbolo
sentiment_for_symbols, all_news_entries = get_sentiment_for_all_symbols(symbol_list)

# Ordinare i simboli in base al sentiment medio (decrescente)
sorted_symbols = sorted(sentiment_for_symbols.items(), key=lambda x: x[1], reverse=True)

# Crea il contenuto del file classifica.html
html_classifica = ["<html><head><title>Classifica dei Simboli</title></head><body>",
                   "<h1>Classifica dei Simboli in Base alla Probabilità di Crescita</h1>",
                   "<table border='1'><tr><th>Simbolo</th><th>Probabilità</th></tr>"]

for symbol, probability in sorted_symbols:
    html_classifica.append(f"<tr><td>{symbol}</td><td>{probability*100:.2f}%</td></tr>")

html_classifica.append("</table></body></html>")

try:
    contents = repo.get_contents(file_path)
    repo.update_file(contents.path, "Updated classification", "\n".join(html_classifica), contents.sha)
except GithubException:
    repo.create_file(file_path, "Created classification", "\n".join(html_classifica))

print("Classifica aggiornata con successo!")

# Creazione del file news.html con i titoli e il sentiment
html_news = ["<html><head><title>Notizie e Sentiment</title></head><body>",
             "<h1>Notizie Finanziarie con Sentiment</h1>",
             "<table border='1'><tr><th>Simbolo</th><th>Notizia</th><th>Sentiment</th></tr>"]

for symbol, title, sentiment in all_news_entries:
    html_news.append(f"<tr><td>{symbol}</td><td>{title}</td><td>{sentiment:.2f}</td></tr>")

html_news.append("</table></body></html>")

try:
    contents = repo.get_contents(news_path)
    repo.update_file(contents.path, "Updated news sentiment", "\n".join(html_news), contents.sha)
except GithubException:
    repo.create_file(news_path, "Created news sentiment", "\n".join(html_news))

print("News aggiornata con successo!")















'''
sentiment_dict = {
    "gain": 0.9,
    "profit": 0.8,
    "growth": 0.7,
    "loss": 0.2,
    "fall": 0.1,
    "crash": 0.0,
    "recovery": 0.9,
    "surge": 0.8,
    "decline": 0.2,
    "positive earnings": 0.9,
    "strong performance": 0.8,
    "high demand": 0.8,
    "negative outlook": 0.1,
    "market crash": 0.0,
    "unexpected loss": 0.2,
    "financial struggle": 0.1,
    "high volatility": 0.2,
    "record profits": 0.85,
    "strong growth": 0.75,
    "stock price increase": 0.8,
    "investor optimism": 0.9,
    "government bailout": 0.7,
    "bankruptcy risk": 0.0,
    "merger talks": 0.8,
    "market stability": 0.6,
    "rising demand": 0.7,
    "cost cutting measures": 0.6,
    "revenue growth": 0.75,
    "product launch": 0.8,
    "price surge": 0.85,
    "slow recovery": 0.3,
    "uncertain market": 0.2,
    "massive loss": 0.0,
    "strong outlook": 0.8,
    "increased revenue": 0.8,
    "profit warning": 0.2,
    "solid performance": 0.7,
    "unexpected gain": 0.9,
    "debt reduction": 0.7,
    "company expansion": 0.8,
    "restructuring plan": 0.6,
    "stock market rally": 0.85,
    "economic recovery": 0.9,
    "consumer spending": 0.7,
    "sharp decline": 0.1,
    "financial crisis": 0.0,
    "stock market drop": 0.1,
    "economic downturn": 0.1,
    "quarterly loss": 0.2,
    "recession fears": 0.0,
    "market correction": 0.2,
    "fiscal policy": 0.5,
    "international growth": 0.7,
    "strong demand": 0.8,
    "cost reduction": 0.6,
    "financial growth": 0.75,
    "job creation": 0.8,
    "inflation concern": 0.3,
    "debt crisis": 0.0,
    "economic boom": 0.9,
    "expansion plans": 0.8,
    "strategic alliance": 0.7,
    "low interest rates": 0.7,
    "positive forecast": 0.8,
    "market recovery": 0.9,
    "shareholder value": 0.75,
    "market confidence": 0.8,
    "new product": 0.8,
    "debt restructuring": 0.7,
    "bankruptcy filing": 0.0,
    "dividend increase": 0.8,
    "improved outlook": 0.8,
    "strong market position": 0.8,
    "cash flow": 0.7,
    "earnings beat": 0.8,
    "profits jump": 0.9,
    "demand surge": 0.8,
    "job growth": 0.75,
    "high profits": 0.8,
    "economic stability": 0.7,
    "market boom": 0.85,
    "interest rate hike": 0.3,
    "financial health": 0.8,
    "credit rating upgrade": 0.7,
    "positive sentiment": 0.9,
    "market volatility": 0.4,
    "price correction": 0.2,
    "exponential growth": 0.9,
    "investor confidence": 0.8,
    "liquidity issues": 0.2,
    "significant loss": 0.1,
    "mild recovery": 0.4,
    "business expansion": 0.8,
    "upward trend": 0.8,
    "cost-cutting initiatives": 0.6,
    "loss of market share": 0.2,
    "corporate restructuring": 0.6,
    "market slowdown": 0.2,
    "strong leadership": 0.75,
    "stock market volatility": 0.4,
    "high profits": 0.8,
    "strategic partnership": 0.7,
    "business acquisition": 0.8,
    "dividend payout": 0.7,
    "earnings report": 0.8,
    "economic growth": 0.8,
    "expansion opportunity": 0.8,
    "risk of default": 0.0,
    "margin improvement": 0.75,
    "price stabilization": 0.6,
    "business strategy": 0.7,
    "capital investment": 0.7,
    "inflation risk": 0.3,
    "retail sales growth": 0.7,
    "consumer confidence": 0.8,
    "economic resilience": 0.8,
    "corporate profit": 0.8,
    "financial performance": 0.7,
    "operational efficiency": 0.7,
    "investment opportunities": 0.8,
    "aggressive growth": 0.9,
    "stock buyback": 0.8,
    "negative growth": 0.2,
    "market rally": 0.8,
    "strong economic performance": 0.8,
    "price increase": 0.7,
    "business diversification": 0.75,
    "economic uncertainty": 0.2,
    "product innovation": 0.8,
    "stable market": 0.7,
    "revenue stream": 0.8,
    "liquidity crisis": 0.0,
    "cash reserves": 0.7,
    "financial outlook": 0.7,
    "geopolitical risk": 0.3,
    "business cycle": 0.6,
    "retail growth": 0.7,
    "international expansion": 0.8,
    "commodity prices": 0.6,
    "macroeconomic indicators": 0.5,
    "disruptive technology": 0.8,
    "market consolidation": 0.7,
    "profit margin": 0.7,
    "market trend": 0.6,
    "record revenue": 0.85,
    "financial strategy": 0.7,
    "business stability": 0.8,
    "operational growth": 0.75,
    "debt load": 0.2,
    "stock price drop": 0.2,
    "poor financial results": 0.1,
    "slow growth": 0.4,
    "inventory growth": 0.6,
    "financial leverage": 0.6,
    "strategic shift": 0.7,
    "negative sentiment": 0.2,
    "capital expenditures": 0.7,
    "profitability concerns": 0.2,
    "business model": 0.6,
    "capital markets": 0.7,
    "product demand": 0.7,
    "company performance": 0.7,
    "stock fluctuations": 0.5,
    "cost-efficiency": 0.7,
    "market share growth": 0.8,
    "economic contraction": 0.2,
    "labor market": 0.6,
    "financial burden": 0.3,
    "debt default": 0.0,
    "asset sale": 0.6,
    "business outlook": 0.7,
    "macroeconomic policy": 0.5,
    "decline in profits": 0.1,
    "asset management": 0.7,
    "overleveraged": 0.1,
    "decline": 0.2,
    "falling": 0.2,
    "drop": 0.2,
    "unreliable": 0.1,
    "intense": 0.3,
    "loss": 0.1,
    "ceased": 0.0,
    "profits": 0.2,
    "scandal": 0.1,
    "revenues": 0.2,
    "compensating": 0.6,
    "improved": 0.7,
    "uncertain": 0.2,
    "potential": 0.1,
    "reducing": 0.2,
    "surge": 0.1,
    "outbreak": 0.1,
    "surcharge": 0.2,
    "impact": 0.3,
    "increase": 0.2,
    "issues": 0.3,
    "rising": 0.3,
    "volatility": 0.2,
    "downturn": 0.1,
    "fears": 0.1,
    "correction": 0.2,
    "policy": 0.5,
    "growth": 0.75,
    "demand": 0.8,
    "reduction": 0.6,
    "creation": 0.8,
    "concern": 0.3,
    "crisis": 0.0,
    "boom": 0.9,
    "plans": 0.8,
    "alliance": 0.7,
    "rates": 0.7,
    "forecast": 0.8,
    "recovery": 0.9,
    "value": 0.75,
    "confidence": 0.8,
    "product": 0.8,
    "restructuring": 0.7,
    "filing": 0.0,
    "outlook": 0.8,
    "position": 0.8,
    "flow": 0.7,
    "beat": 0.8,
    "jump": 0.9,
    "profits": 0.8,
    "stability": 0.7,
    "hike": 0.3,
    "health": 0.8,
    "upgrade": 0.7,
    "sentiment": 0.9,
    "expansion": 0.8,
    "trend": 0.8,
    "initiatives": 0.6,
    "share": 0.2,
    "slowdown": 0.2,
    "leadership": 0.75,
    "partnership": 0.7,
    "acquisition": 0.8,
    "payout": 0.7,
    "report": 0.8,
    "opportunity": 0.8,
    "default": 0.0,
    "improvement": 0.75,
    "stabilization": 0.6,
    "strategy": 0.7,
    "investment": 0.7,
    "risk": 0.3,
    "resilience": 0.8,
    "profit": 0.8,
    "performance": 0.7,
    "efficiency": 0.7,
    "opportunities": 0.8,
    "buyback": 0.8,
    "rally": 0.8,
    "increase": 0.7,
    "diversification": 0.75,
    "uncertainty": 0.2,
    "innovation": 0.8,
    "stability": 0.7,
    "stream": 0.8,
    "crisis": 0.0,
    "reserves": 0.7,
    "outlook": 0.7,
    "risk": 0.3,
    "cycle": 0.6,
    "growth": 0.7,
    "expansion": 0.8,
    "prices": 0.6,
    "indicators": 0.5,
    "technology": 0.8,
    "consolidation": 0.7,
    "margin": 0.7,
    "trend": 0.6,
    "revenue": 0.85,
    "strategy": 0.7,
    "stability": 0.8,
    "growth": 0.75,
    "load": 0.2,
    "drop": 0.2,
    "results": 0.1,
    "growth": 0.4,
    "growth": 0.6,
    "leverage": 0.6,
    "shift": 0.7,
    "sentiment": 0.2,
    "expenditures": 0.7,
    "concerns": 0.2,
    "model": 0.6,
    "markets": 0.7,
    "demand": 0.7,
    "performance": 0.7,
    "fluctuations": 0.5,
    "efficiency": 0.7,
    "growth": 0.8,
    "contraction": 0.2,
    "market": 0.6,
    "burden": 0.3,
    "default": 0.0,
    "sale": 0.6,
    "outlook": 0.7,
    "policy": 0.5,
    "profits": 0.1,
    "management": 0.7,
    "decline in customer trust": 0.2,
    "falling customer trust": 0.2,
    "predicted drop in shoppers": 0.2,
    "unreliable marketplaces": 0.1,
    "intense competition": 0.3,
    "reported loss": 0.1,
    "ceased operations": 0.0,
    "profits drop": 0.2,
    "car finance scandal": 0.1,
    "decline in revenues": 0.2,
    "compensating customers": 0.6,
    "improved performance": 0.7,
    "uncertain future": 0.2,
    "potential exit": 0.1,
    "reducing workforce": 0.2,
    "egg cost surge": 0.1,
    "bird-flu outbreak": 0.1,
    "surcharge per egg": 0.2,
    "inflation impact": 0.3,
    "price increase": 0.2,
    "supply chain issues": 0.3,
    "rising costs": 0.3,
    "market volatility": 0.2,
    "stock market drop": 0.1,
    "economic downturn": 0.1,
    "quarterly loss": 0.2,
    "recession fears": 0.1,
    "market correction": 0.2,
    "fiscal policy": 0.5,
    "international growth": 0.7,
    "strong demand": 0.8,
    "cost reduction": 0.6,
    "financial growth": 0.75,
    "job creation": 0.8,
    "inflation concern": 0.3,
    "debt crisis": 0.0,
    "economic boom": 0.9,
    "expansion plans": 0.8,
    "strategic alliance": 0.7,
    "low interest rates": 0.7,
    "positive forecast": 0.8,
    "market recovery": 0.9,
    "shareholder value": 0.75,
    "market confidence": 0.8,
    "new product": 0.8,
    "debt restructuring": 0.7,
    "bankruptcy filing": 0.0,
    "dividend increase": 0.8,
    "improved outlook": 0.8,
    "strong market position": 0.8,
    "cash flow": 0.7,
    "earnings beat": 0.8,
    "profits jump": 0.9,
    "demand surge": 0.8,
    "job growth": 0.75,
    "high profits": 0.8,
    "economic stability": 0.7,
    "market boom": 0.85,
    "interest rate hike": 0.3,
    "financial health": 0.8,
    "credit rating upgrade": 0.7,
    "positive sentiment": 0.9,
    "market volatility": 0.4,
    "price correction": 0.2,
    "exponential growth": 0.9,
    "investor confidence": 0.8,
    "liquidity issues": 0.2,
    "significant loss": 0.1,
    "mild recovery": 0.4,
    "business expansion": 0.8,
    "upward trend": 0.8,
    "cost-cutting initiatives": 0.6,
    "loss of market share": 0.2,
    "corporate restructuring": 0.6,
    "market slowdown": 0.2,
    "strong leadership": 0.75,
    "stock market volatility": 0.4,
    "high profits": 0.8,
    "strategic partnership": 0.7,
    "business acquisition": 0.8,
    "dividend payout": 0.7,
    "earnings report": 0.8,
    "economic growth": 0.8,
    "expansion opportunity": 0.8,
    "risk of default": 0.0,
    "margin improvement": 0.75,
    "price stabilization": 0.6,
    "business strategy": 0.7,
    "capital investment": 0.7,
    "inflation risk": 0.3,
    "retail sales growth": 0.7,
    "consumer confidence": 0.8,
    "economic resilience": 0.8,
    "corporate profit": 0.8,
    "financial performance": 0.7,
    "operational efficiency": 0.7,
    "investment opportunities": 0.8,
    "aggressive growth": 0.9,
    "stock buyback": 0.8,
    "negative growth": 0.2,
    "market rally": 0.8,
    "strong economic performance": 0.8,
    "price increase": 0.7,
    "business diversification": 0.75,
    "economic uncertainty": 0.2,
    "product innovation": 0.8,
    "stable market": 0.7,
    "revenue stream": 0.8,
    "liquidity crisis": 0.0,
    "cash reserves": 0.7,
    "financial outlook": 0.7,
    "geopolitical risk": 0.3,
    "business cycle": 0.6,
    "retail growth": 0.7,
    "international expansion": 0.8,
    "commodity prices": 0.6,
    "macroeconomic indicators": 0.5,
    "disruptive technology": 0.8,
    "market consolidation": 0.7,
    "profit margin": 0.7,
    "market trend": 0.6,
    "record revenue": 0.85,
    "financial strategy": 0.7,
    "business stability": 0.8,
    "operational growth": 0.75,
    "debt load": 0.2,
    "stock price drop": 0.2,
    "poor financial results": 0.1,
    "slow growth": 0.4,
    "inventory growth": 0.6,
    "financial leverage": 0.6,
    "strategic shift": 0.7,
    "negative sentiment": 0.2,
    "capital expenditures": 0.7,
    "profitability concerns": 0.2,
    "business model": 0.6,
    "capital markets": 0.7,
    "product demand": 0.7,
    "company performance": 0.7,
    "stock fluctuations": 0.5,
    "cost-efficiency": 0.7,
    "market share growth": 0.8,
    "economic contraction": 0.2,
    "labor market": 0.6,
    "financial burden": 0.3,
    "debt default": 0.0,
    "asset sale": 0.6,
    "business outlook": 0.7,
    "macroeconomic policy": 0.5,
    "decline in profits": 0.1,
    "asset management": 0.7,
    "overleveraged": 0.1
}
'''
