import re
import feedparser

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO_NAME = "VecorDEV/dati-finanziari"


# Lista dei simboli azionari da cercare
symbol_list = ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "V", "JPM", "JNJ", "WMT",
        "NVDA", "PYPL", "DIS", "NFLX", "NIO", "NRG", "ADBE", "INTC", "CSCO", "PFE",
        "KO", "PEP", "MRK", "ABT", "XOM", "CVX", "T", "MCD", "NKE", "HD",
        "IBM", "CRM", "BMY", "ORCL", "ACN", "LLY", "QCOM", "HON", "COST", "SBUX",
        "CAT", "LOW", "MS", "GS", "AXP", "INTU", "AMGN", "GE", "FIS", "CVS",
        "DE", "BDX", "NOW", "SCHW", "LMT", "ADP", "C", "PLD", "NSC", "TMUS",
        "ITW", "FDX", "PNC", "SO", "APD", "ADI", "ICE", "ZTS", "TJX", "CL",
        "MMC", "EL", "GM", "CME", "EW", "AON", "D", "PSA", "AEP", "TROW", 
        "LNTH", "HE", "BTDR", "NAAS", "SCHL", "TGT", "SYK", "BKNG", "DUK", "USB",
        "EURUSD", "USDJPY", "GBPUSD", "AUDUSD", "USDCAD", "USDCHF", "NZDUSD", "EURGBP", "EURJPY", "GBPJPY",
        "AUDJPY", "CADJPY", "CHFJPY", "EURAUD", "EURNZD", "EURCAD", "EURCHF", "GBPCHF", "GBPJPY", "AUDCAD",
        "BTCUSD", "ETHUSD", "LTCUSD", "XRPUSD", "BCHUSD", "EOSUSD", "XLMUSD", "ADAUSD", "TRXUSD", "NEOUSD",
        "DASHUSD", "XMRUSD", "ETCUSD", "ZECUSD", "BNBUSD", "DOGEUSD", "USDTUSD", "LINKUSD", "ATOMUSD", "XTZUSD",
        "CCUSD", "XAUUSD", "XAGUSD", "GCUSD", "ZSUSX", "CTUSX", "ZCUSX", "OJUSX", "RBUSD"]  # Puoi aggiungere altri simboli

def get_stock_news(symbol):
    """ Recupera i titoli delle notizie per un determinato simbolo. """
    url = f"https://news.google.com/rss/search?q={symbol}+stock&hl=en-US&gl=US&ceid=US:en"
    feed = feedparser.parse(url)
    
    titles = [entry.title for entry in feed.entries]
    print(titles)
    return titles

# Dizionario di parole chiave con il loro punteggio di sentiment
# Dataset esteso di parole e frasi con i rispettivi punteggi
sentiment_dict = {
    "gain": 0.9,
    "profit": 0.8,
    "growth": 0.7,
    "loss": 0.2,
    "fall": 0.1,
    "crash": 0.0,
    "recovery": 0.9,
    "surge": 0.8,
    "decline": 0.2,
    "positive earnings": 0.9,
    "strong performance": 0.8,
    "high demand": 0.8,
    "negative outlook": 0.1,
    "market crash": 0.0,
    "unexpected loss": 0.2,
    "financial struggle": 0.1,
    "high volatility": 0.2,
    "record profits": 0.85,
    "strong growth": 0.75,
    "stock price increase": 0.8,
    "investor optimism": 0.9,
    "government bailout": 0.7,
    "bankruptcy risk": 0.0,
    "merger talks": 0.8,
    "market stability": 0.6,
    "rising demand": 0.7,
    "cost cutting measures": 0.6,
    "revenue growth": 0.75,
    "product launch": 0.8,
    "price surge": 0.85,
    "slow recovery": 0.3,
    "uncertain market": 0.2,
    "massive loss": 0.0,
    "strong outlook": 0.8,
    "increased revenue": 0.8,
    "profit warning": 0.2,
    "solid performance": 0.7,
    "unexpected gain": 0.9,
    "debt reduction": 0.7,
    "company expansion": 0.8,
    "restructuring plan": 0.6,
    "stock market rally": 0.85,
    "economic recovery": 0.9,
    "consumer spending": 0.7,
    "sharp decline": 0.1,
    "financial crisis": 0.0,
    "stock market drop": 0.1,
    "economic downturn": 0.1,
    "quarterly loss": 0.2,
    "recession fears": 0.0,
    "market correction": 0.2,
    "fiscal policy": 0.5,
    "international growth": 0.7,
    "strong demand": 0.8,
    "cost reduction": 0.6,
    "financial growth": 0.75,
    "job creation": 0.8,
    "inflation concern": 0.3,
    "debt crisis": 0.0,
    "economic boom": 0.9,
    "expansion plans": 0.8,
    "strategic alliance": 0.7,
    "low interest rates": 0.7,
    "positive forecast": 0.8,
    "market recovery": 0.9,
    "shareholder value": 0.75,
    "market confidence": 0.8,
    "new product": 0.8,
    "debt restructuring": 0.7,
    "bankruptcy filing": 0.0,
    "dividend increase": 0.8,
    "improved outlook": 0.8,
    "strong market position": 0.8,
    "cash flow": 0.7,
    "earnings beat": 0.8,
    "profits jump": 0.9,
    "demand surge": 0.8,
    "job growth": 0.75,
    "high profits": 0.8,
    "economic stability": 0.7,
    "market boom": 0.85,
    "interest rate hike": 0.3,
    "financial health": 0.8,
    "credit rating upgrade": 0.7,
    "positive sentiment": 0.9,
    "market volatility": 0.4,
    "price correction": 0.2,
    "exponential growth": 0.9,
    "investor confidence": 0.8,
    "liquidity issues": 0.2,
    "significant loss": 0.1,
    "mild recovery": 0.4,
    "business expansion": 0.8,
    "upward trend": 0.8,
    "cost-cutting initiatives": 0.6,
    "loss of market share": 0.2,
    "corporate restructuring": 0.6,
    "market slowdown": 0.2,
    "strong leadership": 0.75,
    "stock market volatility": 0.4,
    "high profits": 0.8,
    "strategic partnership": 0.7,
    "business acquisition": 0.8,
    "dividend payout": 0.7,
    "earnings report": 0.8,
    "economic growth": 0.8,
    "expansion opportunity": 0.8,
    "risk of default": 0.0,
    "margin improvement": 0.75,
    "price stabilization": 0.6,
    "business strategy": 0.7,
    "capital investment": 0.7,
    "inflation risk": 0.3,
    "retail sales growth": 0.7,
    "consumer confidence": 0.8,
    "economic resilience": 0.8,
    "corporate profit": 0.8,
    "financial performance": 0.7,
    "operational efficiency": 0.7,
    "investment opportunities": 0.8,
    "aggressive growth": 0.9,
    "stock buyback": 0.8,
    "negative growth": 0.2,
    "market rally": 0.8,
    "strong economic performance": 0.8,
    "price increase": 0.7,
    "business diversification": 0.75,
    "economic uncertainty": 0.2,
    "product innovation": 0.8,
    "stable market": 0.7,
    "revenue stream": 0.8,
    "liquidity crisis": 0.0,
    "cash reserves": 0.7,
    "financial outlook": 0.7,
    "geopolitical risk": 0.3,
    "business cycle": 0.6,
    "retail growth": 0.7,
    "international expansion": 0.8,
    "commodity prices": 0.6,
    "macroeconomic indicators": 0.5,
    "disruptive technology": 0.8,
    "market consolidation": 0.7,
    "profit margin": 0.7,
    "market trend": 0.6,
    "record revenue": 0.85,
    "financial strategy": 0.7,
    "business stability": 0.8,
    "operational growth": 0.75,
    "debt load": 0.2,
    "stock price drop": 0.2,
    "poor financial results": 0.1,
    "slow growth": 0.4,
    "inventory growth": 0.6,
    "financial leverage": 0.6,
    "strategic shift": 0.7,
    "negative sentiment": 0.2,
    "capital expenditures": 0.7,
    "profitability concerns": 0.2,
    "business model": 0.6,
    "capital markets": 0.7,
    "product demand": 0.7,
    "company performance": 0.7,
    "stock fluctuations": 0.5,
    "cost-efficiency": 0.7,
    "market share growth": 0.8,
    "economic contraction": 0.2,
    "labor market": 0.6,
    "financial burden": 0.3,
    "debt default": 0.0,
    "asset sale": 0.6,
    "business outlook": 0.7,
    "macroeconomic policy": 0.5,
    "decline in profits": 0.1,
    "asset management": 0.7,
    "overleveraged": 0.1,
    "decline": 0.2,
    "falling": 0.2,
    "drop": 0.2,
    "unreliable": 0.1,
    "intense": 0.3,
    "loss": 0.1,
    "ceased": 0.0,
    "profits": 0.2,
    "scandal": 0.1,
    "revenues": 0.2,
    "compensating": 0.6,
    "improved": 0.7,
    "uncertain": 0.2,
    "potential": 0.1,
    "reducing": 0.2,
    "surge": 0.1,
    "outbreak": 0.1,
    "surcharge": 0.2,
    "impact": 0.3,
    "increase": 0.2,
    "issues": 0.3,
    "rising": 0.3,
    "volatility": 0.2,
    "downturn": 0.1,
    "fears": 0.1,
    "correction": 0.2,
    "policy": 0.5,
    "growth": 0.75,
    "demand": 0.8,
    "reduction": 0.6,
    "creation": 0.8,
    "concern": 0.3,
    "crisis": 0.0,
    "boom": 0.9,
    "plans": 0.8,
    "alliance": 0.7,
    "rates": 0.7,
    "forecast": 0.8,
    "recovery": 0.9,
    "value": 0.75,
    "confidence": 0.8,
    "product": 0.8,
    "restructuring": 0.7,
    "filing": 0.0,
    "outlook": 0.8,
    "position": 0.8,
    "flow": 0.7,
    "beat": 0.8,
    "jump": 0.9,
    "profits": 0.8,
    "stability": 0.7,
    "hike": 0.3,
    "health": 0.8,
    "upgrade": 0.7,
    "sentiment": 0.9,
    "expansion": 0.8,
    "trend": 0.8,
    "initiatives": 0.6,
    "share": 0.2,
    "slowdown": 0.2,
    "leadership": 0.75,
    "partnership": 0.7,
    "acquisition": 0.8,
    "payout": 0.7,
    "report": 0.8,
    "opportunity": 0.8,
    "default": 0.0,
    "improvement": 0.75,
    "stabilization": 0.6,
    "strategy": 0.7,
    "investment": 0.7,
    "risk": 0.3,
    "resilience": 0.8,
    "profit": 0.8,
    "performance": 0.7,
    "efficiency": 0.7,
    "opportunities": 0.8,
    "buyback": 0.8,
    "rally": 0.8,
    "increase": 0.7,
    "diversification": 0.75,
    "uncertainty": 0.2,
    "innovation": 0.8,
    "stability": 0.7,
    "stream": 0.8,
    "crisis": 0.0,
    "reserves": 0.7,
    "outlook": 0.7,
    "risk": 0.3,
    "cycle": 0.6,
    "growth": 0.7,
    "expansion": 0.8,
    "prices": 0.6,
    "indicators": 0.5,
    "technology": 0.8,
    "consolidation": 0.7,
    "margin": 0.7,
    "trend": 0.6,
    "revenue": 0.85,
    "strategy": 0.7,
    "stability": 0.8,
    "growth": 0.75,
    "load": 0.2,
    "drop": 0.2,
    "results": 0.1,
    "growth": 0.4,
    "growth": 0.6,
    "leverage": 0.6,
    "shift": 0.7,
    "sentiment": 0.2,
    "expenditures": 0.7,
    "concerns": 0.2,
    "model": 0.6,
    "markets": 0.7,
    "demand": 0.7,
    "performance": 0.7,
    "fluctuations": 0.5,
    "efficiency": 0.7,
    "growth": 0.8,
    "contraction": 0.2,
    "market": 0.6,
    "burden": 0.3,
    "default": 0.0,
    "sale": 0.6,
    "outlook": 0.7,
    "policy": 0.5,
    "profits": 0.1,
    "management": 0.7,
    "decline in customer trust": 0.2,
    "falling customer trust": 0.2,
    "predicted drop in shoppers": 0.2,
    "unreliable marketplaces": 0.1,
    "intense competition": 0.3,
    "reported loss": 0.1,
    "ceased operations": 0.0,
    "profits drop": 0.2,
    "car finance scandal": 0.1,
    "decline in revenues": 0.2,
    "compensating customers": 0.6,
    "improved performance": 0.7,
    "uncertain future": 0.2,
    "potential exit": 0.1,
    "reducing workforce": 0.2,
    "egg cost surge": 0.1,
    "bird-flu outbreak": 0.1,
    "surcharge per egg": 0.2,
    "inflation impact": 0.3,
    "price increase": 0.2,
    "supply chain issues": 0.3,
    "rising costs": 0.3,
    "market volatility": 0.2,
    "stock market drop": 0.1,
    "economic downturn": 0.1,
    "quarterly loss": 0.2,
    "recession fears": 0.1,
    "market correction": 0.2,
    "fiscal policy": 0.5,
    "international growth": 0.7,
    "strong demand": 0.8,
    "cost reduction": 0.6,
    "financial growth": 0.75,
    "job creation": 0.8,
    "inflation concern": 0.3,
    "debt crisis": 0.0,
    "economic boom": 0.9,
    "expansion plans": 0.8,
    "strategic alliance": 0.7,
    "low interest rates": 0.7,
    "positive forecast": 0.8,
    "market recovery": 0.9,
    "shareholder value": 0.75,
    "market confidence": 0.8,
    "new product": 0.8,
    "debt restructuring": 0.7,
    "bankruptcy filing": 0.0,
    "dividend increase": 0.8,
    "improved outlook": 0.8,
    "strong market position": 0.8,
    "cash flow": 0.7,
    "earnings beat": 0.8,
    "profits jump": 0.9,
    "demand surge": 0.8,
    "job growth": 0.75,
    "high profits": 0.8,
    "economic stability": 0.7,
    "market boom": 0.85,
    "interest rate hike": 0.3,
    "financial health": 0.8,
    "credit rating upgrade": 0.7,
    "positive sentiment": 0.9,
    "market volatility": 0.4,
    "price correction": 0.2,
    "exponential growth": 0.9,
    "investor confidence": 0.8,
    "liquidity issues": 0.2,
    "significant loss": 0.1,
    "mild recovery": 0.4,
    "business expansion": 0.8,
    "upward trend": 0.8,
    "cost-cutting initiatives": 0.6,
    "loss of market share": 0.2,
    "corporate restructuring": 0.6,
    "market slowdown": 0.2,
    "strong leadership": 0.75,
    "stock market volatility": 0.4,
    "high profits": 0.8,
    "strategic partnership": 0.7,
    "business acquisition": 0.8,
    "dividend payout": 0.7,
    "earnings report": 0.8,
    "economic growth": 0.8,
    "expansion opportunity": 0.8,
    "risk of default": 0.0,
    "margin improvement": 0.75,
    "price stabilization": 0.6,
    "business strategy": 0.7,
    "capital investment": 0.7,
    "inflation risk": 0.3,
    "retail sales growth": 0.7,
    "consumer confidence": 0.8,
    "economic resilience": 0.8,
    "corporate profit": 0.8,
    "financial performance": 0.7,
    "operational efficiency": 0.7,
    "investment opportunities": 0.8,
    "aggressive growth": 0.9,
    "stock buyback": 0.8,
    "negative growth": 0.2,
    "market rally": 0.8,
    "strong economic performance": 0.8,
    "price increase": 0.7,
    "business diversification": 0.75,
    "economic uncertainty": 0.2,
    "product innovation": 0.8,
    "stable market": 0.7,
    "revenue stream": 0.8,
    "liquidity crisis": 0.0,
    "cash reserves": 0.7,
    "financial outlook": 0.7,
    "geopolitical risk": 0.3,
    "business cycle": 0.6,
    "retail growth": 0.7,
    "international expansion": 0.8,
    "commodity prices": 0.6,
    "macroeconomic indicators": 0.5,
    "disruptive technology": 0.8,
    "market consolidation": 0.7,
    "profit margin": 0.7,
    "market trend": 0.6,
    "record revenue": 0.85,
    "financial strategy": 0.7,
    "business stability": 0.8,
    "operational growth": 0.75,
    "debt load": 0.2,
    "stock price drop": 0.2,
    "poor financial results": 0.1,
    "slow growth": 0.4,
    "inventory growth": 0.6,
    "financial leverage": 0.6,
    "strategic shift": 0.7,
    "negative sentiment": 0.2,
    "capital expenditures": 0.7,
    "profitability concerns": 0.2,
    "business model": 0.6,
    "capital markets": 0.7,
    "product demand": 0.7,
    "company performance": 0.7,
    "stock fluctuations": 0.5,
    "cost-efficiency": 0.7,
    "market share growth": 0.8,
    "economic contraction": 0.2,
    "labor market": 0.6,
    "financial burden": 0.3,
    "debt default": 0.0,
    "asset sale": 0.6,
    "business outlook": 0.7,
    "macroeconomic policy": 0.5,
    "decline in profits": 0.1,
    "asset management": 0.7,
    "overleveraged": 0.1
}

def calculate_sentiment(titles):
    """ Calcola il sentiment medio di una lista di titoli di notizie. """
    total_sentiment = 0
    num_titles = len(titles)
    
    for title in titles:
        sentiment_score = 0
        for keyword, score in sentiment_dict.items():
            if re.search(r'\b' + re.escape(keyword) + r'\b', title.lower()):
                sentiment_score += score
        total_sentiment += sentiment_score
    
    if num_titles > 0:
        average_sentiment = total_sentiment / num_titles
    else:
        average_sentiment = 0  # Se non ci sono titoli, il sentiment è 0
    
    return average_sentiment

def get_sentiment_for_all_symbols(symbol_list):
    sentiment_results = {}
    
    for symbol in symbol_list:
        titles = get_stock_news(symbol)
        sentiment = calculate_sentiment(titles)
        sentiment_results[symbol] = sentiment
    
    return sentiment_results

# Calcolare il sentiment medio per ogni simbolo
sentiment_for_symbols = get_sentiment_for_all_symbols(symbol_list)

# Stampare i risultati
for symbol, sentiment in sentiment_for_symbols.items():
    print(f"Symbol: {symbol}, Average Sentiment: {sentiment}")



def create_classification_file():
    # Ordina la lista di simboli per probabilità (decrescente) e per nome (alfabetico) in caso di probabilità uguali
    sorted_symbols = sorted(sentiment_for_symbols, key=lambda x: (-x[1], x[0]))

    # Crea il contenuto del file HTML
    html_content = []
    html_content.append("<html><head><title>Classifica dei Simboli</title></head><body>")
    html_content.append("<h1>Classifica dei Simboli in Base alla Probabilità di Crescita</h1>")
    html_content.append("<table border='1'><tr><th>Simbolo</th><th>Probabilità</th></tr>")
    
    # Aggiungi ogni simbolo e la sua probabilità alla tabella HTML
    for symbol, probability in sorted_symbols:
        html_content.append(f"<tr><td>{symbol}</td><td>{probability:.2f}%</td></tr>")
    
    html_content.append("</table></body></html>")

    # Salva il file HTML nella cartella 'results'
    file_path = "results/classifica.html"
    
    # Salva il file su GitHub
    github = Github(GITHUB_TOKEN)
    repo = github.get_repo(REPO_NAME)
    try:
        contents = repo.get_contents(file_path)
        repo.update_file(contents.path, "Updated classification", "\n".join(html_content), contents.sha)
    except GithubException:
        # Se il file non esiste, creiamo un nuovo file
        repo.create_file(file_path, "Created classification", "\n".join(html_content))
    
    print("Classifica aggiornata con successo!")

