name: Aggiorna macro segnali

on:
  workflow_dispatch:  # Trigger manuale
  schedule:
    - cron: '0 8 * * *'  # Esegui ogni giorno alle 8:00 AM UTC

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Assicurati che la versione di Python sia corretta

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential python3-dev  # Installa dipendenze di compilazione

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools

    - name: Install dependencies
      run: |
        pip install yfinance fredapi pandas numpy
          
    - name: Run prediction script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token GitHub con permessi di scrittura sul repository
      run: python scripts/predict_MACRO.py  # Percorso corretto del tuo codice
