name: Calcolo Indicatori Tecnici

on:
  schedule:
    - cron: '0 7 * * *'  # Ogni giorno alle 07:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Esegui lo script Python
      run: python scripts/indicators.py

    - name: Commit e push dei risultati
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add result/indicatori.html
        git commit -m "Aggiorna indicatori tecnici [$(date +'%Y-%m-%d')]" || echo "Nessuna modifica da committare"
        git push
