name: Calcola Indicatori Tecnici

on:
  schedule:
    - cron: "0 6 * * *"  # ogni giorno alle 6:00 UTC
  workflow_dispatch:      # abilita avvio manuale

jobs:
  run-indicators:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui script
        run: python scripts/indicators.py

      - name: Carica file HTML degli indicatori
        uses: actions/upload-artifact@v4
        with:
          name: indicatori-tecnici
          path: results/indicatori.html
