name: Calcolo Indicatori Tecnici

on:
  schedule:
    - cron: '0 7 * * *'  # Esegue ogni giorno alle 7:00 UTC
  workflow_dispatch:      # Eseguibile anche manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Esegui lo script Python
      run: python script.py

    - name: Commit e push dei risultati
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add result/indicatori.html
        git commit -m "Aggiorna indicatori tecnici [$(date +'%Y-%m-%d')]"
        git push
      env:
        # Necessario se il repo usa token personalizzati
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # O puoi usare token PAT per push su repo privato
        # PAT: ${{ secrets.PAT }}
