name: Run Code Automatically and Manually

on:
  workflow_dispatch:  # Trigger manuale
  schedule:
    - cron: '0 8 * * *'  # Esegui ogni giorno alle 8:00 AM UTC

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 scikit-learn xgboost PyGithub pandas numpy
        pip install feedparser
        pip install selenium
        pip install selenium webdriver-manager
        

    - name: Run prediction script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token GitHub con permessi di scrittura sul repository
      run: python scripts/predict_PRO.py  # Percorso corretto del tuo codice
