name: Run Code Automatically and Manually

on:
  workflow_dispatch:  # Trigger manuale
  #schedule:
    #- cron: '0 8 * * *'  # Esegui ogni giorno alle 8:00 AM UTC

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Assicurati che la versione di Python sia corretta

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential python3-dev  # Installa dipendenze di compilazione

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 scikit-learn xgboost PyGithub pandas numpy feedparser
        pip install cython murmurhash  # Installa dipendenze di compilazione
        pip install spacy==3.0.6  # Installa una versione stabile di spaCy
        python -m spacy download en_core_web_sm  # Scarica il modello linguistico per spaCy
        #pip install textblob

    - name: Run prediction script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token GitHub con permessi di scrittura sul repository
      run: python scripts/predict_stock.py  # Percorso corretto del tuo codice
